#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Healthcare.Android.Resource", IsApplication=true)]

namespace Healthcare.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SomeLogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int AnotherAddress = 2131034129;
			
			// aapt resource value: 0x7f05002b
			public const int Benefits = 2131034155;
			
			// aapt resource value: 0x7f050000
			public const int BenefitsHeader = 2131034112;
			
			// aapt resource value: 0x7f05002c
			public const int Claims = 2131034156;
			
			// aapt resource value: 0x7f050021
			public const int Contact = 2131034145;
			
			// aapt resource value: 0x7f050009
			public const int Coverage = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int CurrentLocation = 2131034128;
			
			// aapt resource value: 0x7f05002d
			public const int Dashboard = 2131034157;
			
			// aapt resource value: 0x7f050013
			public const int DisclaimerLabel = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int DistanceListView = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int EffectiveFromLabel = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int EffectiveUntilLabel = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int Email = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int EnableIdViewing = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int FAQ = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int Footer = 2131034142;
			
			// aapt resource value: 0x7f05000e
			public const int FromLabel = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int Goup = 2131034119;
			
			// aapt resource value: 0x7f050018
			public const int Header = 2131034136;
			
			// aapt resource value: 0x7f05001f
			public const int IdCard = 2131034143;
			
			// aapt resource value: 0x7f050023
			public const int Label1 = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int Label2 = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int LastActivity = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int LastCleaning = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int LastDentalVisit = 2131034150;
			
			// aapt resource value: 0x7f050001
			public const int Logo = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int NetworkListView = 2131034124;
			
			// aapt resource value: 0x7f050027
			public const int Options = 2131034151;
			
			// aapt resource value: 0x7f050014
			public const int OptionsLabel = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int PlanBennefits = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int PlanCoverageLabel = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int PlanName = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int PlanNetworkLabel = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int Print = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int Privacy = 2131034138;
			
			// aapt resource value: 0x7f050020
			public const int Providers = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int Register = 2131034141;
			
			// aapt resource value: 0x7f050029
			public const int Row1Options = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int Row2Options = 2131034154;
			
			// aapt resource value: 0x7f050012
			public const int SearchProviders = 2131034130;
			
			// aapt resource value: 0x7f05001c
			public const int SignIn = 2131034140;
			
			// aapt resource value: 0x7f05000b
			public const int SpecialtyListView = 2131034123;
			
			// aapt resource value: 0x7f050019
			public const int Tips = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int Usage = 2131034122;
			
			// aapt resource value: 0x7f050022
			public const int Welcome = 2131034146;
			
			// aapt resource value: 0x7f050034
			public const int dateOfBirth = 2131034164;
			
			// aapt resource value: 0x7f050030
			public const int firstName = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int instructions = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int lastName = 2131034161;
			
			// aapt resource value: 0x7f05002e
			public const int linearLayout = 2131034158;
			
			// aapt resource value: 0x7f050032
			public const int memberId = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int next = 2131034166;
			
			// aapt resource value: 0x7f050033
			public const int password = 2131034163;
			
			// aapt resource value: 0x7f05000f
			public const int radiogroup = 2131034127;
			
			// aapt resource value: 0x7f050035
			public const int zipCode = 2131034165;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Benefits = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FindProvider = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int IdCard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PortalDashboard = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
